### ISSUE TITLE
possible issue with mod during crafting

### ISSUE THREAD

**Issue by kreezxil** [Shadows-of-Fire/FastWorkbench#13]
making a stone pickaxe

I had 6 sticks for the handle and put 64 cobble for the head. The I shift click the output. I got 6 pickaxes as expected but then the cobble head part of the recipe remained and it thought to itself, oh he wants slabs, let's mass make those too. and now I got 72 slabs.

Expected result:
6 pickaxes and then I'd have to reconsider using the remaining cobble for something else.

similar thing happened with torches
had 4 sticks and put a stack of coal on top, got 16 torches and suddenly 56 coal dust.

mods in the pack i'm building:
http://paste.ubuntu.com/p/3d88r53yRx/

**Comment by psath** [comment]
This is still present in 1.7.1 (at least in FTB Interactions 1.5.0)

The added checkMatrixChanges check at https://github.com/Shadows-of-Fire/FastWorkbench/blob/master/src/main/java/shadows/fastbench/gui/ContainerFastBench.java#L81 always evaluates to true because it is only ever called immediately after it is reset to true at https://github.com/Shadows-of-Fire/FastWorkbench/blob/master/src/main/java/shadows/fastbench/gui/ContainerFastBench.java#L135
thus, the CraftingManager is still queried for a matching recipe in all the cases it would have been before b145e90

**Comment by Shadows-of-Fire** [comment]
Everything about your statement is wrong.  The issue is not still present, nor do you even appear to understand how that method is called.  The *manual* call I do there is not impacted, but the other (up to 576) calls are.
