### ISSUE TITLE
fastworkbench and crafting tweaks conflict

### ISSUE THREAD

**Issue by Willy347** [Shadows-of-Fire/FastWorkbench#27]
when both these mods are installed:
CraftingTweaks_1.14.4-10.1.3 (BlayTheNinth)
FastWorkbench-1.14.4-2.1.0 

the balance/spread button stops working but the keybinding does still work.

also reported to craftingtweaks

**Comment by blay09** [comment]
I assume this is due to FastWorkbench clearing the button list if removeRecipeBook is enabled.

https://github.com/Shadows-of-Fire/FastWorkbench/blob/1.14/src/main/java/shadows/fastbench/gui/GuiFastBench.java#L18

Instead, it should only find and remove the recipe book button so that buttons added via the InitGui event remain in place.

**Comment by Shadows-of-Fire** [comment]
Does the initgui event fire before that?  I thought it was broken because i didnt hook up the imc calls yet

**Comment by blay09** [comment]
Actually, only the Pre event fires before .init(), but Crafting Tweaks adds the buttons in Post, so it should be unaffected. However, I think the real problem here is that you're only removing the recipe book button from "buttons", but not from "children", causing it to eat up the click events still (as event handling uses "children").

**Comment by Shadows-of-Fire** [comment]
Hooked up the IMC calls again, this should work fine now.

**Comment by blay09** [comment]
The problem persists, see my comment above

> I think the real problem here is that you're only removing the recipe book button from "buttons", but not from "children", causing it to eat up the click events still (as event handling uses "children").
